### PR TITLE
Check in vendor directory.

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title, it's what all go projects do.

### CODE REVIEW

**Comment by jcrossley3** [comment]
Thanks for the extra 6000 files. Really.

**Comment by jcrossley3** [comment]
Point of fact regarding "what all go projects do" @markusthoemmes https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory

**Comment by matzew** [comment]
```
+2,354,139
```

solid! :-)

**Comment by markusthoemmes** [comment]
@jcrossley3 Because Golang projects are not aware of their own dependencies the way that Java dependencies are. If I switch branches, Java IDEs will make sure the deps are correct as well. This is not happening for Golang projects (at least to my knowledge).

The Pros in your link outweigh the cons for me as well. Especially as we have "master" references in Gopkg.lock, which might resolve differently for anybody.

Lastly, `dep ensure` just doesn't feel solid to me. I often need to manually remove the whole vendor directory to make it pass reliably and stuff like that.

**Comment by markusthoemmes** [comment]
Also: All upstream projects we care about do it, so it's a more consistent workflow for us to do it as well.

**Comment by jcrossley3** [comment]
I got it down to a couple thousand with a prune. I hope you're happy now.

**Pull request closed without merging**
